### ISSUE TITLE
Brak pola Imię i Nazwisko w tabeli User

### ISSUE THREAD

**Issue by Atteru** [Atteru/Tripper-GroupProject#1]
Proszę o dodanie w bazie danych w tabeli User pola mieszczącego Imię i Nazwisko użytkownika.

Sugeruję nazwę: Name

**Comment by ebeabar** [comment]
Pole Imie i Nazwisko zgodnie ze specyfikacja nie są wymagane (w ogole nie sa wspomniane). Jedyne wymagane pola to nazwa uzytkownika i haslo, co jest zawarte w tabeli Traveler.
