### ISSUE TITLE
Walidacja danych podczas logowania

### ISSUE THREAD

**Issue by ebeabar** [Atteru/Tripper-GroupProject#3]
Brak walidacji, czy użytkownik istnieje - można się zalogowac wpisujac cokolwiek.

**Comment by Atteru** [comment]
Ready for delivery to main branch, will be delivered with next release

**Comment by Atteru** [comment]
Delivered to master, ready for verification

**Comment by ebeabar** [comment]
Twoj commit powoduje 7 errorow przez co nie da sie zbudowac projektu. Powodem jest prawdopodobnie brak klasy i tabeli w bazie pt. User (jest Traveler).
![user_bledy](https://user-images.githubusercontent.com/26083109/33515667-cb354402-d766-11e7-87b1-225e537417c6.png)

**Comment by Atteru** [comment]
1, 2, 4, 5 błąd wynika z niezapowiedzianej zmiany projektowej w Bazie danych (Zmiana tabeli User na Traveler (pomimo że dalej jestem zdania że tabela powinna być przywrócona do pierwotnej formy) jest to poprawione w commicie który zaraz puszczę
Za błąd 3 i 6 możesz podziękować osobie która wpieprza się w mój kod i bez żadnych informacji zaczyna go modyfikować (również to poprawiłem)

**Comment by Atteru** [comment]
Fixed
